periodic_table = {
    1: {"Name": "Hydrogen", "Symbol": "H", "Atomic Mass": 1.008},
    2: {"Name": "Helium", "Symbol": "He", "Atomic Mass": 4.0026},
    3: {"Name": "Lithium", "Symbol": "Li", "Atomic Mass": 6.94},
    4: {"Name": "Beryllium", "Symbol": "Be", "Atomic Mass": 9.0122},
    5: {"Name": "Boron", "Symbol": "B", "Atomic Mass": 10.81},
    6: {"Name": "Carbon", "Symbol": "C", "Atomic Mass": 12.011},
    7: {"Name": "Nitrogen", "Symbol": "N", "Atomic Mass": 14.007},
    8: {"Name": "Oxygen", "Symbol": "O", "Atomic Mass": 15.999},
    9: {"Name": "Fluorine", "Symbol": "F", "Atomic Mass": 18.998},
    10: {"Name": "Neon", "Symbol": "Ne", "Atomic Mass": 20.180},
    11: {"Name": "Sodium", "Symbol": "Na", "Atomic Mass": 22.990},
    12: {"Name": "Magnesium", "Symbol": "Mg", "Atomic Mass": 24.305},
    13: {"Name": "Aluminium", "Symbol": "Al", "Atomic Mass": 26.982},
    14: {"Name": "Silicon", "Symbol": "Si", "Atomic Mass": 28.085},
    15: {"Name": "Phosphorus", "Symbol": "P", "Atomic Mass": 30.974},
    16: {"Name": "Sulfur", "Symbol": "S", "Atomic Mass": 32.06},
    17: {"Name": "Chlorine", "Symbol": "Cl", "Atomic Mass": 35.45},
    18: {"Name": "Argon", "Symbol": "Ar", "Atomic Mass": 39.948},
    19: {"Name": "Potassium", "Symbol": "K", "Atomic Mass": 39.098},
    20: {"Name": "Calcium", "Symbol": "Ca", "Atomic Mass": 40.078},
    21: {"Name": "Scandium", "Symbol": "Sc", "Atomic Mass": 44.956},
    22: {"Name": "Titanium", "Symbol": "Ti", "Atomic Mass": 47.867},
    23: {"Name": "Vanadium", "Symbol": "V", "Atomic Mass": 50.942},
    24: {"Name": "Chromium", "Symbol": "Cr", "Atomic Mass": 51.996},
    25: {"Name": "Manganese", "Symbol": "Mn", "Atomic Mass": 54.938},
    26: {"Name": "Iron", "Symbol": "Fe", "Atomic Mass": 55.845},
    27: {"Name": "Cobalt", "Symbol": "Co", "Atomic Mass": 58.933},
    28: {"Name": "Nickel", "Symbol": "Ni", "Atomic Mass": 58.693},
    29: {"Name": "Copper", "Symbol": "Cu", "Atomic Mass": 63.546},
    30: {"Name": "Zinc", "Symbol": "Zn", "Atomic Mass": 65.38},
    31: {"Name": "Gallium", "Symbol": "Ga", "Atomic Mass": 69.723},
    32: {"Name": "Germanium", "Symbol": "Ge", "Atomic Mass": 72.630},
    33: {"Name": "Arsenic", "Symbol": "As", "Atomic Mass": 74.922},
    34: {"Name": "Selenium", "Symbol": "Se", "Atomic Mass": 78.971},
    35: {"Name": "Bromine", "Symbol": "Br", "Atomic Mass": 79.904},
    36: {"Name": "Krypton", "Symbol": "Kr", "Atomic Mass": 83.798},
    37: {"Name": "Rubidium", "Symbol": "Rb", "Atomic Mass": 85.468},
    38: {"Name": "Strontium", "Symbol": "Sr", "Atomic Mass": 87.62},
    39: {"Name": "Yttrium", "Symbol": "Y", "Atomic Mass": 88.906},
    40: {"Name": "Zirconium", "Symbol": "Zr", "Atomic Mass": 91.224},
    41: {"Name": "Niobium", "Symbol": "Nb", "Atomic Mass": 92.906},
    42: {"Name": "Molybdenum", "Symbol": "Mo", "Atomic Mass": 95.95},
    43: {"Name": "Technetium", "Symbol": "Tc", "Atomic Mass": 98},
    44: {"Name": "Ruthenium", "Symbol": "Ru", "Atomic Mass": 101.07},
    45: {"Name": "Rhodium", "Symbol": "Rh", "Atomic Mass": 102.91},
    46: {"Name": "Palladium", "Symbol": "Pd", "Atomic Mass": 106.42},
    47: {"Name": "Silver", "Symbol": "Ag", "Atomic Mass": 107.87},
    48: {"Name": "Cadmium", "Symbol": "Cd", "Atomic Mass": 112.41},
    49: {"Name": "Indium", "Symbol": "In", "Atomic Mass": 114.82},
    50: {"Name": "Tin", "Symbol": "Sn", "Atomic Mass": 118.71},
    51: {"Name": "Antimony", "Symbol": "Sb", "Atomic Mass": 121.76},
    52: {"Name": "Tellurium", "Symbol": "Te", "Atomic Mass": 127.60},
    53: {"Name": "Iodine", "Symbol": "I", "Atomic Mass": 126.90},
    54: {"Name": "Xenon", "Symbol": "Xe", "Atomic Mass": 131.29},
    55: {"Name": "Cesium", "Symbol": "Cs", "Atomic Mass": 132.91},
    56: {"Name": "Barium", "Symbol": "Ba", "Atomic Mass": 137.33},
    57: {"Name": "Lanthanum", "Symbol": "La", "Atomic Mass": 138.91},
    58: {"Name": "Cerium", "Symbol": "Ce", "Atomic Mass": 140.12},
    59: {"Name": "Praseodymium", "Symbol": "Pr", "Atomic Mass": 140.91},
    60: {"Name": "Neodymium", "Symbol": "Nd", "Atomic Mass": 144.24},
    61: {"Name": "Promethium", "Symbol": "Pm", "Atomic Mass": 145},
    62: {"Name": "Samarium", "Symbol": "Sm", "Atomic Mass": 150.36},
    63: {"Name": "Europium", "Symbol": "Eu", "Atomic Mass": 151.96},
    64: {"Name": "Gadolinium", "Symbol": "Gd", "Atomic Mass": 157.25},
    65: {"Name": "Terbium", "Symbol": "Tb", "Atomic Mass": 158.93},
    66: {"Name": "Dysprosium", "Symbol": "Dy", "Atomic Mass": 162.50},
    67: {"Name": "Holmium", "Symbol": "Ho", "Atomic Mass": 164.93},
    68: {"Name": "Erbium", "Symbol": "Er", "Atomic Mass": 167.26},
    69: {"Name": "Thulium", "Symbol": "Tm", "Atomic Mass": 168.93},
    70: {"Name": "Ytterbium", "Symbol": "Yb", "Atomic Mass": 173.05},
    71: {"Name": "Lutetium", "Symbol": "Lu", "Atomic Mass": 174.97},
    72: {"Name": "Hafnium", "Symbol": "Hf", "Atomic Mass": 178.49},
    73: {"Name": "Tantalum", "Symbol": "Ta", "Atomic Mass": 180.95},
    74: {"Name": "Tungsten", "Symbol": "W", "Atomic mass" : 183.84},
    75: {"Name": "Rhenium", "Symbol": "Re", "Atomic Mass": 186.21},
    76: {"Name": "Osmium", "Symbol": "Os", "Atomic Mass": 190.23},
    77: {"Name": "Iridium", "Symbol": "Ir", "Atomic Mass": 192.22},
    78: {"Name": "Platinum", "Symbol": "Pt", "Atomic Mass": 195.08},
    79: {"Name": "Gold", "Symbol": "Au", "Atomic Mass": 196.97},
    80: {"Name": "Mercury", "Symbol": "Hg", "Atomic Mass": 200.59},
    81: {"Name": "Thallium", "Symbol": "Tl", "Atomic Mass": 204.38},
    82: {"Name": "Lead", "Symbol": "Pb", "Atomic Mass": 207.2},
    83: {"Name": "Bismuth", "Symbol": "Bi", "Atomic Mass": 208.98},
    84: {"Name": "Polonium", "Symbol": "Po", "Atomic Mass": 209},
    85: {"Name": "Astatine", "Symbol": "At", "Atomic Mass": 210},
    86: {"Name": "Radon", "Symbol": "Rn", "Atomic Mass": 222},
    87: {"Name": "Francium", "Symbol": "Fr", "Atomic Mass": 223},
    88: {"Name": "Radium", "Symbol": "Ra", "Atomic Mass": 226},
    89: {"Name": "Actinium", "Symbol": "Ac", "Atomic Mass": 227},
    90: {"Name": "Thorium", "Symbol": "Th", "Atomic Mass": 232.04},
    91: {"Name": "Protactinium", "Symbol": "Pa", "Atomic Mass": 231.04},
    92: {"Name": "Uranium", "Symbol": "U", "Atomic Mass": 238.03},
    93: {"Name": "Neptunium", "Symbol": "Np", "Atomic Mass": 237},
    94: {"Name": "Plutonium", "Symbol": "Pu", "Atomic Mass": 244},
    95: {"Name": "Americium", "Symbol": "Am", "Atomic Mass": 243},
    96: {"Name": "Curium", "Symbol": "Cm", "Atomic Mass": 247},
    97: {"Name": "Berkelium", "Symbol": "Bk", "Atomic Mass": 247},
    98: {"Name": "Californium", "Symbol": "Cf", "Atomic Mass": 251},
    99: {"Name": "Einsteinium", "Symbol": "Es", "Atomic Mass": 252},
    100: {"Name": "Fermium", "Symbol": "Fm", "Atomic Mass": 257},
    101: {"Name": "Mendelevium", "Symbol": "Md", "Atomic Mass": 258},
    102: {"Name": "Nobelium", "Symbol": "No", "Atomic Mass": 259},
    103: {"Name": "Lawrencium", "Symbol": "Lr", "Atomic Mass": 266},
    104: {"Name": "Rutherfordium", "Symbol": "Rf", "Atomic Mass": 267},
    105: {"Name": "Dubnium", "Symbol": "Db", "Atomic Mass": 268},
    106: {"Name": "Seaborgium", "Symbol": "Sg", "Atomic Mass": 269},
    107: {"Name": "Bohrium", "Symbol": "Bh", "Atomic Mass": 270},
    108: {"Name": "Hassium", "Symbol": "Hs", "Atomic Mass": 277},
    109: {"Name": "Meitnerium", "Symbol": "Mt", "Atomic Mass": 278},
    110: {"Name": "Darmstadtium", "Symbol": "Ds", "Atomic Mass": 281},
    111: {"Name": "Roentgenium", "Symbol": "Rg", "Atomic Mass": 282},
    112: {"Name": "Copernicium", "Symbol": "Cn", "Atomic Mass": 285},
    113: {"Name": "Nihonium", "Symbol": "Nh", "Atomic Mass": 286},
    114: {"Name": "Flerovium", "Symbol": "Fl", "Atomic Mass": 289},
    115: {"Name": "Moscovium", "Symbol": "Mc", "Atomic Mass": 290},
    116: {"Name": "Livermorium", "Symbol": "Lv", "Atomic Mass": 293},
    117: {"Name": "Tennessine", "Symbol": "Ts", "Atomic Mass": 294},
    118: {"Name": "Oganesson", "Symbol": "Og", "Atomic Mass": 294}
}
try:
    atomic_number = int(input("🔍 Enter atomic number (1–118): "))
    if atomic_number in periodic_table:
        element = periodic_table[atomic_number]
        print("\n🧪 Element Information:")
        print(f"Name: {element['Name']}")
        print(f"Symbol: {element['Symbol']}")
        print(f"Atomic Mass: {element['Atomic Mass']}")
    else:
        print("⚠️ Invalid atomic number. Please enter a number between 1 and 118.")
except ValueError:
    print("❌ Please enter a valid integer.")
   
